package client.views;

import client.components.RoundedBorder;
import java.awt.*;
import server.models.BookingSummary;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;

import java.awt.image.BufferedImage;

public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    private BookingSummary summary;

    public Receipt() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public Receipt(BookingSummary summary) {
        this.summary = summary;
        initComponents();
        fillData();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void fillData() {
        lblBookingCode.setText(summary.getBookingCode());

        // MENGUBAH WARNA STATUS MENJADI HIJAU
        String status = summary.getStatus();
        lblStatus.setText(status);
        if (status != null) {
            if (status.equalsIgnoreCase("CONFIRMED")) {
                lblStatus.setForeground(new Color(14, 173, 0)); // hijau
                lblStatus.setFont(lblStatus.getFont().deriveFont(Font.BOLD));
            }
        }

        lblBookingDate.setText(summary.getDate());
        lblTrainNumber.setText(summary.getTrainNumber());
        lblBookingName.setText(summary.getBookingName());
        lblClass.setText(summary.getKelas());
        lblCarriages.setText(String.valueOf(summary.getCarriages()));
        lblDepartureTime.setText(summary.getDepartureTime());
        lblRoute.setText(
                summary.getOrigin() + " - " + summary.getDestination()
        );
        lblPrice.setText(formatRupiah(summary.getCost()));
        lblAdditionalCost.setText(formatRupiah(summary.getAdditionalCost()));
        lblTotalCost.setText(formatRupiah(summary.getTotalCost()));

        // MEMBUAT QRCODE & BARCODE
        generateQRCode(summary.getBookingCode());
    }

    // MENGUBAH FORMAT HARGA MENJADI MATA UANG RUPIAH
    private String formatRupiah(int value) {
        return "Rp " + String.format("%,d", value).replace(',', '.');
    }

    private void generateQRCode(String text) {
        try {
            QRCodeWriter writer = new QRCodeWriter();
            BitMatrix matrix = writer.encode(text, BarcodeFormat.QR_CODE, 150, 150);
            BufferedImage image = MatrixToImageWriter.toBufferedImage(matrix);
            lblQRCode.setText("");
            lblQRCode.setIcon(new javax.swing.ImageIcon(image));
        } catch (WriterException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        roundedPanel1 = new client.components.RoundedPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cumagaris = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cumagaris2 = new javax.swing.JPanel();
        lblBookingCode = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblBookingDate = new javax.swing.JLabel();
        lblTrainNumber = new javax.swing.JLabel();
        lblBookingName = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblCarriages = new javax.swing.JLabel();
        lblDepartureTime = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblAdditionalCost = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblQRCode = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblRoute = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new RoundedBorder(20, new Color(68, 68, 68), 1));

        jLabel19.setFont(new java.awt.Font("Inter 18pt Black", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(68, 68, 68));
        jLabel19.setText("UBD Express");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-train-50.png"))); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compresskaru_logo ubd_50x50.png"))); // NOI18N

        roundedPanel1.setBackground(new java.awt.Color(68, 68, 68));

        jLabel30.setFont(new java.awt.Font("Inter 18pt Black", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Ticket Reservation Information");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 13, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(68, 68, 68));
        jLabel21.setText("Booking Code :");

        jLabel22.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(68, 68, 68));
        jLabel22.setText("Status :");

        jLabel23.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(68, 68, 68));
        jLabel23.setText("Booking Date :");

        cumagaris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 68, 68)));

        javax.swing.GroupLayout cumagarisLayout = new javax.swing.GroupLayout(cumagaris);
        cumagaris.setLayout(cumagarisLayout);
        cumagarisLayout.setHorizontalGroup(
            cumagarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cumagarisLayout.setVerticalGroup(
            cumagarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel24.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(68, 68, 68));
        jLabel24.setText("Train Number :");

        jLabel25.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(68, 68, 68));
        jLabel25.setText("Booking Name :");

        jLabel26.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(68, 68, 68));
        jLabel26.setText("Class :");

        jLabel27.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(68, 68, 68));
        jLabel27.setText("Depature Time :");

        jLabel28.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(68, 68, 68));
        jLabel28.setText("Route :");

        cumagaris2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 68, 68)));

        javax.swing.GroupLayout cumagaris2Layout = new javax.swing.GroupLayout(cumagaris2);
        cumagaris2.setLayout(cumagaris2Layout);
        cumagaris2Layout.setHorizontalGroup(
            cumagaris2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cumagaris2Layout.setVerticalGroup(
            cumagaris2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblBookingCode.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblBookingCode.setForeground(new java.awt.Color(68, 68, 68));
        lblBookingCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBookingCode.setText("-");

        lblStatus.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(68, 68, 68));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("-");

        lblBookingDate.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblBookingDate.setForeground(new java.awt.Color(68, 68, 68));
        lblBookingDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBookingDate.setText("-");

        lblTrainNumber.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblTrainNumber.setForeground(new java.awt.Color(68, 68, 68));
        lblTrainNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrainNumber.setText("-");

        lblBookingName.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblBookingName.setForeground(new java.awt.Color(68, 68, 68));
        lblBookingName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBookingName.setText("-");

        lblClass.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblClass.setForeground(new java.awt.Color(68, 68, 68));
        lblClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClass.setText("-");

        lblCarriages.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblCarriages.setForeground(new java.awt.Color(68, 68, 68));
        lblCarriages.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarriages.setText("-");

        lblDepartureTime.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblDepartureTime.setForeground(new java.awt.Color(68, 68, 68));
        lblDepartureTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDepartureTime.setText("-");

        jLabel38.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(68, 68, 68));
        jLabel38.setText("Additional Cost :");

        jLabel39.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(68, 68, 68));
        jLabel39.setText("Total Cost :");

        lblAdditionalCost.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblAdditionalCost.setForeground(new java.awt.Color(68, 68, 68));
        lblAdditionalCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdditionalCost.setText("-");

        lblTotalCost.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblTotalCost.setForeground(new java.awt.Color(68, 68, 68));
        lblTotalCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCost.setText("-");

        jLabel42.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(68, 68, 68));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Thank You  For Using Our Service, Have A Pleasant Trip!");

        lblQRCode.setText("Buat barcode ");

        jLabel43.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(68, 68, 68));
        jLabel43.setText("Carriages :");

        lblRoute.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblRoute.setForeground(new java.awt.Color(68, 68, 68));
        lblRoute.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRoute.setText("-");

        jLabel40.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(68, 68, 68));
        jLabel40.setText("Price :");

        lblPrice.setFont(new java.awt.Font("Inter 18pt Black", 1, 12)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(68, 68, 68));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrice.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(237, 237, 237)
                                .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cumagaris2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cumagaris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBookingCode, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(lblBookingDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel43))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDepartureTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCarriages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBookingName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTrainNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRoute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAdditionalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                        .addGap(15, 15, 15))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblQRCode)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblBookingCode))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblBookingDate))
                .addGap(18, 18, 18)
                .addComponent(cumagaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblTrainNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblBookingName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblClass))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarriages)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDepartureTime)
                        .addGap(18, 18, 18)
                        .addComponent(lblRoute))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)))
                .addGap(18, 18, 18)
                .addComponent(cumagaris2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lblAdditionalCost))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(lblTotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQRCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cumagaris;
    private javax.swing.JPanel cumagaris2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdditionalCost;
    private javax.swing.JLabel lblBookingCode;
    private javax.swing.JLabel lblBookingDate;
    private javax.swing.JLabel lblBookingName;
    private javax.swing.JLabel lblCarriages;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblRoute;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel lblTrainNumber;
    private client.components.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
