
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        layoutlogin.setPreferredSize(new Dimension(450, 500));
    layoutlogin.setSize(450, 500);
    layoutlogin.setMinimumSize(new Dimension(450, 500));
    layoutlogin.setMaximumSize(new Dimension(450, 500));
    
    layoutlogin.revalidate();
    layoutlogin.repaint();
    
     this.setLocationRelativeTo(null);


    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutlogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitleAcc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        layoutlogin.setBackground(new java.awt.Color(255, 255, 255));
        layoutlogin.setBorder(new RoundedBorder(20, new java.awt.Color(0,0,0), 1));
        layoutlogin.setMaximumSize(new java.awt.Dimension(400, 450));
        layoutlogin.setMinimumSize(new java.awt.Dimension(400, 450));
        layoutlogin.setPreferredSize(new java.awt.Dimension(400, 450));
        layoutlogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Inter 28pt", 1, 27)); // NOI18N
        lblTitle.setText("UBD Express");
        layoutlogin.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        lblTitleAcc.setFont(new java.awt.Font("Inter 18pt Medium", 0, 18)); // NOI18N
        lblTitleAcc.setText("Account");
        layoutlogin.add(lblTitleAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-train-50.png"))); // NOI18N
        layoutlogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblUsername.setFont(new java.awt.Font("Inter 18pt Medium", 1, 16)); // NOI18N
        lblUsername.setText("Username :");
        layoutlogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextField1.setBorder(null);
        layoutlogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 290, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        layoutlogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, -1));

        lblPassword.setFont(new java.awt.Font("Inter 18pt Medium", 1, 16)); // NOI18N
        lblPassword.setText("Password :");
        layoutlogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jPasswordField1.setBorder(null);
        layoutlogin.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        layoutlogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 290, 10));

        btnLogin.setFont(new java.awt.Font("Inter 18pt", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new RoundedBorder(20, new java.awt.Color(0,0,0), 1));
        layoutlogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, 30));

        getContentPane().add(layoutlogin, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel layoutlogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleAcc;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
